version: '3.7'

services:
  mhac_api:
    image: mhac_api
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn fast_api:app --host 0.0.0.0 --port 8000"]
    ports:
      - 8000:8000
      - 5678:5678

